//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.AbonentServNamespace {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Abonent", Namespace="http://schemas.datacontract.org/2004/07/AbonentService.Model")]
    [System.SerializableAttribute()]
    public partial class Abonent : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PhoneOperatorIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PhoneOperatorId {
            get {
                return this.PhoneOperatorIdField;
            }
            set {
                if ((this.PhoneOperatorIdField.Equals(value) != true)) {
                    this.PhoneOperatorIdField = value;
                    this.RaisePropertyChanged("PhoneOperatorId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AbonentServNamespace.IAbonentServiceClass")]
    public interface IAbonentServiceClass {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAbonentServiceClass/GetAbonents", ReplyAction="http://tempuri.org/IAbonentServiceClass/GetAbonentsResponse")]
        Server.AbonentServNamespace.Abonent[] GetAbonents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAbonentServiceClass/GetAbonents", ReplyAction="http://tempuri.org/IAbonentServiceClass/GetAbonentsResponse")]
        System.Threading.Tasks.Task<Server.AbonentServNamespace.Abonent[]> GetAbonentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAbonentServiceClass/IncreaseSaldo", ReplyAction="http://tempuri.org/IAbonentServiceClass/IncreaseSaldoResponse")]
        void IncreaseSaldo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAbonentServiceClass/IncreaseSaldo", ReplyAction="http://tempuri.org/IAbonentServiceClass/IncreaseSaldoResponse")]
        System.Threading.Tasks.Task IncreaseSaldoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAbonentServiceClassChannel : Server.AbonentServNamespace.IAbonentServiceClass, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AbonentServiceClassClient : System.ServiceModel.ClientBase<Server.AbonentServNamespace.IAbonentServiceClass>, Server.AbonentServNamespace.IAbonentServiceClass {
        
        public AbonentServiceClassClient() {
        }
        
        public AbonentServiceClassClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AbonentServiceClassClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AbonentServiceClassClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AbonentServiceClassClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Server.AbonentServNamespace.Abonent[] GetAbonents() {
            return base.Channel.GetAbonents();
        }
        
        public System.Threading.Tasks.Task<Server.AbonentServNamespace.Abonent[]> GetAbonentsAsync() {
            return base.Channel.GetAbonentsAsync();
        }
        
        public void IncreaseSaldo() {
            base.Channel.IncreaseSaldo();
        }
        
        public System.Threading.Tasks.Task IncreaseSaldoAsync() {
            return base.Channel.IncreaseSaldoAsync();
        }
    }
}
