//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.OperatorServNamespace {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhoneOperatorData", Namespace="http://schemas.datacontract.org/2004/07/OperatorService.Model")]
    [System.SerializableAttribute()]
    public partial class PhoneOperatorData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SymbolField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Symbol {
            get {
                return this.SymbolField;
            }
            set {
                if ((object.ReferenceEquals(this.SymbolField, value) != true)) {
                    this.SymbolField = value;
                    this.RaisePropertyChanged("Symbol");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OperatorServNamespace.IOperatorServiceClass")]
    public interface IOperatorServiceClass {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperatorServiceClass/GetOperatorData", ReplyAction="http://tempuri.org/IOperatorServiceClass/GetOperatorDataResponse")]
        Server.OperatorServNamespace.PhoneOperatorData[] GetOperatorData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperatorServiceClass/GetOperatorData", ReplyAction="http://tempuri.org/IOperatorServiceClass/GetOperatorDataResponse")]
        System.Threading.Tasks.Task<Server.OperatorServNamespace.PhoneOperatorData[]> GetOperatorDataAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOperatorServiceClassChannel : Server.OperatorServNamespace.IOperatorServiceClass, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OperatorServiceClassClient : System.ServiceModel.ClientBase<Server.OperatorServNamespace.IOperatorServiceClass>, Server.OperatorServNamespace.IOperatorServiceClass {
        
        public OperatorServiceClassClient() {
        }
        
        public OperatorServiceClassClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OperatorServiceClassClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperatorServiceClassClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperatorServiceClassClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Server.OperatorServNamespace.PhoneOperatorData[] GetOperatorData() {
            return base.Channel.GetOperatorData();
        }
        
        public System.Threading.Tasks.Task<Server.OperatorServNamespace.PhoneOperatorData[]> GetOperatorDataAsync() {
            return base.Channel.GetOperatorDataAsync();
        }
    }
}
